#!/bin/bash

# Create a .go file that defines a slice of each
# test line in slogtest.go

(
echo "// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by 'go generate'. DO NOT EDIT.
//go:generate ./mkdescs.sh

package slogtest

var descriptions = []string{"

grep -E '^\s+l\.' slogtest.go | sed -E 's/^\s+(.*)/`\1`,/'

echo "}"
)  | gofmt > descriptions.go.tmp && mv descriptions.go.tmp descriptions.go
